# Experiment parameters
VERBOSE = 5
DEBUG = True
EXP_DEVICE = 'mea' # The device used for the experiment.
EXP_SEEDS = [0] # The RNG seeds used for the experiment.
EXP_DATASEEDS = [100] # The RNG seeds used for data splitting.
EXP_RESTART = True # Whether to restart the experiment at every execution.
EPOCHS = 1 # Number of training epochs for the experiment.

# Experiment details
EXP_MODE = 'test' # Default 'test'. Either 'train', 'test', or 'traintest'. Whether you want to run the experiment in training mode, test mode, or both.
DISH_ID = 'CHIR_N1_DIV48' # The name of the dish in use for the experiment.
EXP_DATASET = 'mnist' # Default 'mnist'. Either 'mnist', 'cifar10', or 'cifar100', or the name of a custom JSON pattern dataset. The name of the dataset you want to use.
TST_SAMPLES = [3, 6] # The slice of dataset you want to use for testing.
TRN_SAMPLES_PER_CLASS = 100 # How many train samples per class you want to use for tetanization.
CUSTOM_DATASET_REPEATS = 25 # Default 25. How many times each stimulus presentation is repeated when a custom JSON pattern dataset is used. Samples are presented in a random order. It is also possible to specify a deterministic sequence as a list
DETECT_EDGES = True # Whether to run edge detection on image samples.
EXP_NAME = EXP_DATASET # The name that you want to assign to this experiment. This will be the name of the folder where the results are stored.

# Device parameters
nh, nw = 64, 64 # Device size.
ENDIANNESS = '<' # Default '<'. Device representation endianness ('<' for little endian, '>' for big endian).
D_MIN, D_MAX, A_MIN, A_MAX = 0, 4095, -8000., 8000. # DA params.
samplingRate = 20000.0 # Sampling frequency of data frames from MEA electrodes.
acquisitionTimePeriod = 100 # Period in ms to record data from BioCam.
calibrationBlanking = 6 # None to disable. Default 0. Calibration blanking value.
calibrationInterval = 400 # None to disable. Default 400. Calibration interval in ms.
amplifBias = 550 # None to disable. Set to 'auto' for automatic calibration. Default 550. Amplifier voltage offset in mV.
amplifShutOff = 2500 # None to disable. Default 1500. Calibration time, i.e. amount of time in us that the amplifiers are shut off during stimulation.

# Stimulation parameters
STIM_MODE = 'pulse' # Default 'pulse'. Either 'pulse' or 'burst'. The type of stmiulation to be used for the experiment.
MAX_FIRING_LIKELIHOOD = 0.33 # Default 1.0. Maximum likelihood that an electrode can fire at a given instant of time, when a stimulus is delivered. Reducing this parameter creates a sparser representation, but allows to preserve the electordes lifetime for longer.
FIRING_BINS = 1 # Default 1. Number of bins to divide stimulation interval for spike train delivey.
STIM_AMPLITUDE = -5 # Stimulus pulse amplitude in uA.
STIM_WIDTH = 20 # Stimulus pulse duration in us.
STIM_INTERVAL = 10 # Time interval in seconds between consecutive stimuli.
STIM_DURATION = 1 # Duration of the stimulation in milliseconds.
STIM_MAX_FREQ = 1000 # Maximum frequency of the spike-encoded stimulus.
TET_STIM_AMPLITUDE = 1 # Stimulus pulse amplitude in uA.
TET_STIM_WIDTH = 5 # Stimulus pulse duration in us.
TET_DURATION = 400 # Duration of the tetanus in milliseconds.
TET_MAX_FREQ = 10 # Maximum frequency of the spike-encoded tetanus.
RECORD_TIME = [2, 2] # Time duration in seconds of the recording before and after a stimulus.

# Compression and saving parameters
HP_FILTER_FREQ = 100 # None to disable. Default 100. Frequency in Hz of the high-pass filter
HP_FILTER_ORDER = 2 # Default 2. Order of the high-pass filter.
COMPR_WINDOW = 2 # Default 2. Size of the spike detection window in milliseconds.
COMPR_SIGMA_THR = 10 # Default 8. Threshold for the spike detection algorithm.
COMPR_SAVE_WIDTH = 3 # Default 3. Number of milliseconds of spike form to save before and after a detected spike.
GLOBAL_RESPONSE_W_START = 0 # Default 0. Window start time in s for the global response copmutation. The global response is computed as the number of spikes generated by the whole dish after a single input presentation on a given time window. This allows to have an online overview of the stimulation effects on the dish.
GLOBAL_RESPONSE_W_END = 5e-3 # Default 0. Window end time in s for the global response copmutation.
GLOBAL_RESPONSE_W_ANTISYMM = True # Default True. Wether to use antysimmetric windows, i.e. subtracting the spike count on a specular window before the stimulus in the global response computation.
SAVE_RAW = False # Whether to save the raw trace.
STIM_TIME_PRECISION = 5 # Precision to locate the stimulus delivery time in ms.

